[tool.ruff]
target-version = "py38"
select = [
    "E", "F", "W",
    "A",
    "B",
    "G",
    "I",
    "PT",
    "PTH",
    "RET",
    "SIM",
    "TCH",
    "NPY",
]
# Never enforce `E501` (line length violations) and 'E741' (ambiguous variable names)
# and 'G004' (do not use f-strings in logging)
# and 'A003' (Shadowing python builtins)
# and 'F401' (imported but unused)
# and 'NPY002' (Replace legacy np.random.seed with the newer numpy.random.Generator)
ignore = ["E501", "E741", "G004", "A003", "F401", "NPY002"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "figures/_build",
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
